- .github/actions/tag-jira-release/action.yml
- .github/actions/tag-jira-release/jira_create_release.sh
- .github/actions/tag-jira-release/jira_tag_tickets.sh
- package.json
> release v2.4.0 to main

- package.json
> release v2.4.0 to develop ↣

- .github/actions/tag-jira-release/entrypoint.sh
- .github/actions/tag-jira-release/jira_create_release.sh
The workflow is not successfully tagging more than one jira ticket
https://virdocs.atlassian.net/browse/CORE-1511
> fix: multiple jira ticket tagging issue (CORE-1511)

- .github/workflows/tag-tickets-test.yml
- package.json
> release v2.3.1 to develop ↣

- .github/workflows/check-release.yml
- .github/workflows/release-notes.yml
Hotfix v2.4.1
- https://virdocs.atlassian.net/browse/CORE-1656
> hotfix v2.4.1 to main

- .github/actions/predict-next-version/git_predict_next_version.sh
- .github/actions/tag-jira-release/entrypoint.sh
- .github/actions/tag-jira-release/git_predict_next_version.sh
- package.json
- tooling/scripts/git_predict_next_version.sh
> hotfix-v2.4.1

- .github/actions/tag-jira-release/entrypoint.sh
- .github/actions/tag-jira-release/jira_tag_tickets.sh
- package.json
> hotfix-v2.4.2 to main

- .github/actions/tag-jira-release/entrypoint.sh
> chore: add debugging to main

- package.json
> release v2.4.5 to develop ↣

- .github/workflows/release-notes.yml
- package.json
> release v2.5.0 to main

- package.json
> release v2.5.0 to develop ↣

- .github/actions/confluence-release-notes/action.yml
- .github/actions/confluence-release-notes/jira_get_ticket.sh
- .github/actions/confluence-release-notes/jira_release_notes.sh
- package.json
> release v2.5.1 to main

- package.json
> release v2.5.1 to develop ↣

- .github/actions/predict-next-version/git_predict_next_version.sh
- .github/actions/tag-jira-release/git_predict_next_version.sh
- .github/actions/tag-jira-release/ticket_status.sh
- .github/workflows/tag-tickets-with-release.yml
- tooling/scripts/git_predict_next_version.sh
Workflows are incorrectly identifying the jira tickets in a release.
https://virdocs.atlassian.net/browse/CORE-1729
> fix: find the correct git changes from log (CORE-1729)

- package.json
> release v2.5.2 to develop ↣

- .github/workflows/tag-tickets-with-release.yml
The debug step is erroring out if there are special escape characters
> fix: remove debug step (NO-TICKET)

- .github/workflows/tag-tickets-with-release.yml
- package.json
> release v2.5.3 to main

- package.json
> release v2.5.3 to develop ↣

- .github/workflows/tag-tickets-with-release.yml
- package.json
> release v2.6.0 to main

- package.json
> release v2.7.0 to develop ↣

- .github/actions/validate-pr/validate_pr.sh
- .github/actions/validate-pr/validate_pr_test.sh
We shouldn't put ":" after "fix" word if the jira ticket follows after the semantics prefix
> feat: add an invalid case to validate PR

- .github/actions/tag-jira-release/jira_tag_tickets.sh
- package.json
> release v2.8.1 to main

- .github/actions/validate-pr/validate_pr.sh
- .github/actions/validate-pr/validate_pr_test.sh
- package.json
> release v2.8.1 to develop ↣

- .github/actions/llm/invoke_gemini.js
The model is sometimes overloaded
https://virdocs.atlassian.net/browse/CORE-1736
> fix: return default message on llm failure (CORE-1736)

- .github/actions/llm/invoke_gemini.js
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.8.2
> release v2.8.2 to main

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.8.2
> release v2.8.2 to develop ↣

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.8.3
> release v2.8.3 to develop ↣

- .github/actions/validate-pr/validate_pr.sh
- .github/actions/validate-pr/validate_pr_test.sh
We need to provide clear instructions to developers when errors occur
https://virdocs.atlassian.net/browse/CORE-1725
> feat: enhance error messages (CORE-1725)

- .github/actions/validate-pr/validate_pr.sh
- .github/actions/validate-pr/validate_pr_test.sh
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.9.0
> release v2.9.0 to main

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.9.0
> release v2.9.0 to develop ↣

- .github/workflows/release-notes.yml
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.10.0
> release v2.10.0 to main

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.11.0
> release v2.11.0 to develop ↣

- .github/actions/static-analysis/action.yml
- .github/actions/static-analysis/scan_github_actions.js
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.12.0
> release v2.12.0 to main

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.12.0
> release v2.12.0 to develop ↣

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.13.0
> release v2.13.0 to develop ↣

- .github/actions/static-analysis/layer_dependency_analysis.js
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.13.0
> hotfix v2.13.1 to main

- .github/actions/static-analysis/layer_dependency_analysis.js
- .github/actions/validate-pr/validate_pr.sh
- .github/actions/validate-pr/validate_pr_test.sh
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.13.0
> hotfix v2.13.1 to develop ↣

- .github/actions/static-analysis/action.yml
- .github/actions/static-analysis/scan_github_actions.js
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.14.0
> release v2.14.0 to main

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.14.0
> release v2.14.0 to develop ↣

- .github/actions/static-analysis/action.yml
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.14.0
Includes CORE-2068
> hotfix v2.14.1 to main

- .github/actions/static-analysis/action.yml
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.14.0
> hotfix v2.14.1 to develop ↣

- .github/actions/validate-pr/validate_pr.sh
- .github/actions/validate-pr/validate_pr_test.sh
- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.16.0
> release v2.16.0 to main

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.17.0
> release v2.17.0 to develop ↣

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.18.0
> release v2.18.0 to develop ↣

- package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.19.0
> release v2.19.0 to develop ↣

- .github/actions/auto-pr-description/generate_pr_description.js
When the AI speaks in riddles, we now speak back with clarity. This PR adds a fail-safe to catch malformed responses from the Gemini API, ensuring we don’t silently stumble over missing `parts` or `text`. Now, if the structure isn’t right, we log the issue loud and clear and exit gracefully—no more mysterious crashes in the dark.
https://virdocs.atlassian.net/browse/${ticketId}
> fix: print pull request description error message (NO-TICKET)

- .github/actions/auto-pr-description/generate_pr_description.js
- .github/actions/auto-release-description/generate_pr_description.js
- .github/actions/confluence-release-notes/generate_release_notes.js
- .github/actions/llm/invoke_gemini.js
> feat: 🎸 update model and token size (#119)
