VirdocsSoftware/github-actions

.github/workflows/devops-vars.yml
The devops-vars jobs are "push" focused. This change allows them to run on pull requests and determine values based on a workflow for pull requests.
=> feat: support pull request workflows

.github/workflows/devops-vars.yml
Many repositories are not setting the variables and assume the `DEVOPS_IS_ENV_DEV` is true for the `develop` branch by default. This change will make that a reality.
=> chore: set default variables for branch names

.github/workflows/tag-tickets-with-release.yml
The tag-tickets-with-release job is not working
https://virdocs.atlassian.net/browse/CORE-1490
=> fix: pass the jira-username as a secret (CORE-1490)

.github/workflows/release-notes.yml
The jira username can be a secret.  Therefore, it has to be treated as one
https://virdocs.atlassian.net/browse/CORE-1661
=> feat: reference jira-username from secrets (CORE-1661)

.github/actions/confluence-release-notes/action.yml, .github/actions/confluence-release-notes/jira_get_ticket.sh, .github/actions/confluence-release-notes/jira_release_notes.sh
The release notes job failed in production.
https://virdocs.atlassian.net/browse/CORE-1661
=> fix: release notes execution error (CORE-1661)

.github/actions/predict-next-version/git_predict_next_version.sh, .github/actions/tag-jira-release/git_predict_next_version.sh, .github/actions/tag-jira-release/ticket_status.sh, .github/workflows/tag-tickets-with-release.yml, package.json, tooling/scripts/git_predict_next_version.sh
=> release v2.5.2 to main

.github/actions/predict-next-version/action.yml, .github/workflows/tag-tickets-with-release.yml
The changes should be compared to the next release version if in develop and the target branch if it is a release
https://virdocs/browse/CORE-1729
=> feat: get the correct git log in shared action (CORE-1729)

.github/actions/validate-pr/action.yml, .github/actions/validate-pr/validate_pr.sh, .github/actions/validate-pr/validate_pr_test.sh, .github/workflows/validate-pr.yml, tooling/scripts/run_tests.sh
✅ Closes: https://virdocs.atlassian.net/browse/CORE-1611
=> feat: 🎸 gitHub actions workflow job to validate PR

.github/actions/validate-pr/action.yml, .github/actions/validate-pr/validate_pr.sh, .github/actions/validate-pr/validate_pr_test.sh, .github/workflows/tag-tickets-with-release.yml, .github/workflows/validate-pr.yml, package.json, tooling/scripts/run_tests.sh
=> release v2.7.0 to main

.github/actions/tag-jira-release/jira_tag_tickets.sh
Cancelled tickets should not be included in a release
https://virdocs/browse/CORE-1691
```
export ticket_info='{"url":"https://virdocs.atlassian.net/browse/CORE-1234","status":"Cancelled"}'
export JIRA_DOMAIN="virdocs.atlassian.net"
echo "$ticket_info" | grep -v '"Done"' | grep -v "Cancelled" | jq -r .url | sort | uniq | sed 's/https:\/\/'$JIRA_DOMAIN'\/browse\///g'
```
The output is an empty string
=> feat: ignore cancelled tickets (CORE-1691)

.github/actions/predict-next-version/git_predict_next_version.sh, .github/actions/tag-jira-release/git_predict_next_version.sh, .github/actions/tag-jira-release/ticket_status.sh, .github/workflows/tag-tickets-with-release.yml, tooling/scripts/git_predict_next_version.sh
Use the same git log command that GitHub does
https://virdocs.atlassian.net/browse/CORE-1734
=> fix: use the correct git log history (CORE-1734)

.github/actions/validate-pr/validate_pr.sh, .github/actions/validate-pr/validate_pr_test.sh
The pr-hygine job is failing to properly compare versions. v2.10.0 is higher than v2.9.0
https://virdocs.atlassian.net/browse/CORE-1873
=> fix: properly compare versions (CORE-1873)

.github/actions/validate-pr/validate_pr.sh, .github/actions/validate-pr/validate_pr_test.sh
This pull request includes minor changes to the PR title validation scripts to improve clarity in the validation messages.
* [`.github/actions/validate-pr/validate_pr.sh`](diffhunk://#diff-a16d0338c335555286965e8bf11685ff11923fea5459cbe5190cfd25047e3a75L82-R83): Updated the example PR title to remove an unnecessary quotation mark and added a note indicating that a new commit is required to update the validation result.
* [`.github/actions/validate-pr/validate_pr_test.sh`](diffhunk://#diff-04960a654e1a0d0d28d2f4a73bf29e448608a542e91fb39eba9c78753c6e11f2L45-R46): Updated the example PR title to remove an unnecessary quotation mark and added a note indicating that a new commit is required to update the validation result.
=> fix: CORE-1638 add to pr hygene error instructions

.github/workflows/release-notes.yml
We need to support creating release notes for all repositories
https://virdocs.atlassian.net/browse/UFA-1014
This pull request includes changes to the `.github/workflows/release-notes.yml` file to add a new input parameter for version tagging and handle its usage in the workflow.
Enhancements to release notes workflow:
* [`.github/workflows/release-notes.yml`](diffhunk://#diff-42244398366244a59eb9bb95d4d4f8f8657297b9e8e5bf3a815f3e8cca374ce1R12-R15): Added a new optional input parameter `version` to allow specifying a version for tagging the release.
* [`.github/workflows/release-notes.yml`](diffhunk://#diff-42244398366244a59eb9bb95d4d4f8f8657297b9e8e5bf3a815f3e8cca374ce1R34-R38): Modified the `Get Version` job to use the provided `version` input if available, otherwise default to …
=> feat: support input version (UFA-1014)

.github/actions/static-analysis/action.yml, .github/actions/static-analysis/scan_github_actions.js
Support ignoring specified github accounts with the default being actions and VirdocsSoftware.
https://virdocs.atlassian.net/browse/RD-2964
This pull request introduces enhancements to the static analysis action by adding support for ignoring specific accounts. The key changes include updates to the action configuration and modifications to the static analysis script to handle the new input.
Enhancements to static analysis action:
* [`.github/actions/static-analysis/action.yml`](diffhunk://#diff-ce5528a1c296df8e97111445d5eb68705a40ead98c9a2e023df580444706422bR4-R9): Added a new input `ignored-accounts` to specify a comma-separated list of accounts to ignore during static analysis. This input is optional and defaults to "actions,VirdocsSoftware". …
=> feat: set default ignored accounts and the ability to specify (RD-2964)

.github/actions/static-analysis/action.yml, .github/actions/static-analysis/layer_dependency_analysis.js, .github/actions/static-analysis/package.json, .github/actions/static-analysis/scan_github_actions.js
https://virdocs.atlassian.net/browse/PAR-2226
This PR enhances the static analysis GitHub Action with two main improvements:
- Expanded scanning to include both `.github/workflows` and all `.github` directories in domain folders
- Improved warning outputs using GitHub Workflow Commands for better visualization
- Added error handling for missing directories
- Added step IDs and controlled error propagation with continue-on-error flags
- Added new functionality to compare package.json dependencies between layers and domains
- Ensures consistent dependency versions between related packages
- Highlights and reports version mismatches as warnings in GitHub workflows
- Added new inputs to specify layer package.json path and domains to analyze
These improvements help maintain code quality and …
=> feat: enhance static file analysis (PAR-2226)

.github/actions/static-analysis/action.yml, .github/actions/static-analysis/layer_dependency_analysis.js, .github/actions/static-analysis/package.json, .github/actions/static-analysis/scan_github_actions.js, package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.13.0
=> release v2.13.0 to main

.github/actions/static-analysis/action.yml, .github/actions/static-analysis/scan_github_actions.js
This PR adds domain-specific scanning capabilities to the static analysis action, making it more flexible and efficient.
https://virdocs.atlassian.net/browse/CORE-2068
- Added support for scanning specific domains using a JSON input format
- Updated the domains input parameter to be optional with a detailed description
- Added DOMAINS environment variable to the scan workflow step
- Maintained backward compatibility for existing workflows
- The `domains` input now accepts a JSON string in the format: `{"include": [{"project": "domain1"}, {"project": "domain2"}]}`
- When domains are specified, the scanner will only check the `.github` directories in the listed domains
- If no domains are specified, the scanner will check all domains (maintaining existing behavior)
- The domain '.' is …
=> feat: Enhanced Static Analysis with Domain-Specific Scanning (CORE-2068)

.github/actions/validate-pr/validate_pr.sh, .github/actions/validate-pr/validate_pr_test.sh
Sometimes a suffix is needed in order to avoid collisions.
This pull request enhances the validate-pr.sh script to support branch names with suffixes (e.g., hotfix/v1.2.3-ar) while still matching the base version (v1.2.3). The changes ensure that branch suffixes do not interfere with version validation logic.
https://virdocs.atlassian.net/browse/CORE-2231
=> feat: support branch suffixes (CORE-2231)

.github/actions/tag-jira-release/jira_tag_tickets.sh, .github/actions/tag-jira-release/ticket_status.sh
Honor the skip-release-notes label on commit messages
https://virdocs.atlassian.net/browse/CORE-2259
```
mfa-prod (active)$ JIRA_DOMAIN=virdocs.atlassian.net ./ticket_status.sh . origin/develop | jq
{
"hash": "6aafce3ed8f6df5250c13c48edd42304b06ac5a8",
"url": "https://virdocs.atlassian.net/browse/CORE-2259",
"status": "In Progress"
}
{
"hash": "db14bb21da7ea4ff50cb71f2456a8e2e686f0444",
"url": "https://virdocs.atlassian.net/browse/CORE-2259",
"status": "In Progress",
"skip-release-notes": true
}
```
=> feat: honor the skip-release-notes label (CORE-2259)

.github/actions/tag-jira-release/jira_create_release.sh, package.json
-Tickets:
- https://virdocs.atlassian.net/issues/?jql=fixVersion%20%3D%20github-actions-v2.18.0
=> release v2.18.0 to main

.github/actions/validate-pr/validate_pr.sh, .github/actions/validate-pr/validate_pr_test.sh
In the spirit of “The Patchwork Paradox,” Team Fox threads another stitch into the fabric of our codebase. This PR introduces support for merging `main` into `develop`—a subtle but essential seam that ensures our past releases and future features stay in sync. Like a well-placed patch, it’s small, but it holds everything together.
=> feat: support merging main to develop

.github/actions/auto-pr-description/generate_pr_description.js, .github/actions/auto-release-description/generate_pr_description.js, .github/actions/confluence-release-notes/generate_release_notes.js, .github/actions/llm/invoke_gemini.js
Upgraded Gemini model references across multiple scripts to ensure consistency and leverage the latest capabilities. Token limits were expanded to accommodate more verbose outputs, giving our AI a bit more room to think before it speaks. Minor deletions were made to clear the path for smarter generation.
https://virdocs.atlassian.net/browse/CORE-246
=> feat: update model and token size (CORE-246)
